name: flutter_share
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  bonsoir: ^6.0.1
  device_info_plus: ^12.3.0
  file_picker: ^10.3.8
  url_launcher: ^6.3.1
  flutter:
    sdk: flutter
  http: ^1.6.0
  network_info_plus: ^7.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  receive_sharing_intent: ^1.8.1
  shelf: ^1.4.2
  shelf_multipart: ^2.0.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.3
  open_filex: ^4.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "android/flutter_share.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/web/
